### ISSUE TITLE
Rule "if turned off" 

### ISSUE THREAD

**Issue by n3roGit** [mwittig/pimatic-milight-reloaded#12] opened 2017-06-22 21:01 UTC
Hi, 

I don't know why but my rules with "if milight-rgbw-zone-3 is off than" doesn't work. 
But is works with my normal 433mhz Switches.

**Comment by mwittig** [comment] 2017-07-15 15:38
For sure, this is caused by the fix for #10 
I need to find a better solution to cover both

**Comment by mwittig** [comment] 2017-07-15 15:53
Should be fixed now with version 0.9.13.

**Closed as completed by mwittig** 2017-07-15 15:53 UTC
Labels: bug
